matrix:
  include:
    - os: linux
      language: android
      android:
        components:
          - build-tools-28.0.3
          - android-28
      jdk: oraclejdk8
      env:
        JAVA_OPTS=-Xmx4g
      script:
        - ./gradlew jsTest testDebugUnitTest --console=plain -Dorg.gradle.parallel=false
    - os: osx
      env:
        JAVA_OPTS=-Xmx4g
      language: java
      jdk: openjdk10
      before_install:
        - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
      script:
        - ./gradlew iosTest --console=plain -Dorg.gradle.parallel=false