version: 2
reference:

  ## Workspaces
  workspace: &workspace
               ~/code

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

  ## Cache
  generate_cache_key: &generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  gradle_key: &gradle_key
                gradle-{{ checksum "/tmp/checksum.txt" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - ~/.android/build-cache

  ## Dependencies
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  ios_config: &ios_config
    working_directory: *workspace
    macos:
      xcode: "10.2.0"
    environment:
      JVM_OPTS: -Xmx3200m

jobs:
  test_android:
    <<: *android_config
    steps:
    - checkout
    - *generate_cache_key
    - *restore_gradle_cache
    - *android_dependencies
    - *save_gradle_cache
    - run:
        name: "Test Android target"
        command: ./gradlew testDebugUnitTest --console=plain -Dorg.gradle.parallel=false

  test_js:
    <<: *android_config
    steps:
      - checkout
      - *generate_cache_key
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - run:
          name: "Test JS target"
          command: ./gradlew jsTest --console=plain -Dorg.gradle.parallel=false

  test_ios:
    <<: *ios_config
    # use a --login shell so our "set Ruby version" command gets picked up for later steps
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run:
          name: Setup environment variables
          command: |
            echo 'export ANDROID_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_HOME="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export ANDROID_SDK_ROOT="/usr/local/share/android-sdk"' >> $BASH_ENV
            echo 'export JAVA_HOME=/Library/Java/Home' >> $BASH_ENV
      - run:
          name: Install Android sdk
          command: |
            HOMEBREW_NO_AUTO_UPDATE=1 brew tap homebrew/cask
            HOMEBREW_NO_AUTO_UPDATE=1 brew cask install android-sdk
      - run:
          name: Install Android dependencies
          command: (yes | sdkmanager "platform-tools" "platforms;android-28" --verbose) || true
      - *generate_cache_key
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache

workflows:
  version: 2
  build:
    jobs:
     - test_android
     - test_js
     - test_ios