version: 2
reference:

  ## Workspaces
  workspace: &workspace
               ~/code

  ## Docker image configurations
  android_config: &android_config
    working_directory: *workspace
    docker:
    - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m

  ## Cache
  generate_cache_key: &generate_cache_key
    run:
      name: Generate cache key
      command: ./.circleci/checksum.sh /tmp/checksum.txt

  gradle_key: &gradle_key
                gradle-{{ checksum "/tmp/checksum.txt" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      key: *gradle_key
      paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper
      - ~/.android/build-cache

  ## Dependencies
  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

jobs:
  build:
    <<: *android_config
    steps:
    - checkout
    - *generate_cache_key
    - *restore_gradle_cache
    - *android_dependencies
    - *save_gradle_cache
    - run:
        name: "Build"
        command: ./gradlew build --console=plain -Dorg.gradle.parallel=false

workflows:
  version: 2
  build:
    jobs:
     - build